apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  # Build and test Web UI
  build-web:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Install dependencies and run tests
        kind: test
        uses: docker://node:20-alpine
        env:
          CI: "true"
        run: |
          set -eu
          cd apps/web
          echo "Installing dependencies..."
          npm ci

          echo "Running linter..."
          npm run lint || true

          echo "Running unit tests..."
          npm run test:unit || true

          echo "Building application..."
          npm run build

      - name: Configure Docker credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ vars.AStack_docker_user }}
          password: ${{ secrets.AStack_docker_token }}

      - name: Calculate base path
        id: basepath
        uses: docker://alpine:3.20
        shell: sh
        env:
          REPOSITORY: ${{ cloudbees.scm.repository }}
          BRANCH: ${{ cloudbees.scm.branch }}
        run: |
          set -eu
          # Extract owner from repository (format: owner/repo)
          ORG=$(echo "$REPOSITORY" | cut -d'/' -f1)

          # Map branch name to environment name
          case "$BRANCH" in
            main)
              ENV_NAME="account-stack-dev"
              ;;
            develop)
              ENV_NAME="account-stack-develop"
              ;;
            staging)
              ENV_NAME="account-stack-staging"
              ;;
            production)
              ENV_NAME="account-stack-prod"
              ;;
            *)
              # For other branches, sanitize branch name for use in path
              ENV_NAME=$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]-' '-' | sed 's/^-*//; s/-*$//')
              ENV_NAME="account-stack-${ENV_NAME}"
              ;;
          esac

          # Construct base path: /org/env
          BASE_PATH="/${ORG}/${ENV_NAME}"
          printf '%s' "$BASE_PATH" > "$CLOUDBEES_OUTPUTS/value"
          echo "Base path: $BASE_PATH"

      - name: Build Docker image
        kind: build
        uses: cloudbees-io/kaniko@v1
        with:
          context: apps/web
          dockerfile: apps/web/Dockerfile
          destination: ${{ vars.AStack_docker_user }}/accountstack-web:${{ cloudbees.scm.sha }}
          build-args: BASE_PATH=${{ steps.basepath.outputs.value }}
          labels: |
            org.opencontainers.image.revision=${{ cloudbees.scm.sha }}

  # Build and test Accounts API
  build-api-accounts:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Run tests
        kind: test
        uses: docker://golang:1.21-alpine
        env:
          CI: "true"
        run: |
          set -eu
          cd apps/api-accounts
          echo "Running Go tests..."
          go test -v -race -coverprofile=coverage.out ./... || true

      - name: Build binary
        uses: docker://golang:1.21-alpine
        run: |
          set -eu
          cd apps/api-accounts
          echo "Building Go binary..."
          go build -o bin/accounts-api cmd/server/main.go

      - name: Configure Docker credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ vars.AStack_docker_user }}
          password: ${{ secrets.AStack_docker_token }}

      - name: Build Docker image
        kind: build
        uses: cloudbees-io/kaniko@v1
        with:
          context: .
          dockerfile: apps/api-accounts/Dockerfile
          destination: ${{ vars.AStack_docker_user }}/accountstack-api-accounts:${{ cloudbees.scm.sha }}
          labels: |
            org.opencontainers.image.revision=${{ cloudbees.scm.sha }}

  # Build and test Transactions API
  build-api-transactions:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Run tests
        kind: test
        uses: docker://golang:1.21-alpine
        env:
          CI: "true"
        run: |
          set -eu
          cd apps/api-transactions
          echo "Running Go tests..."
          go test -v -race -coverprofile=coverage.out ./... || true

      - name: Build binary
        uses: docker://golang:1.21-alpine
        run: |
          set -eu
          cd apps/api-transactions
          echo "Building Go binary..."
          go build -o bin/transactions-api cmd/server/main.go

      - name: Configure Docker credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ vars.AStack_docker_user }}
          password: ${{ secrets.AStack_docker_token }}

      - name: Build Docker image
        kind: build
        uses: cloudbees-io/kaniko@v1
        with:
          context: .
          dockerfile: apps/api-transactions/Dockerfile
          destination: ${{ vars.AStack_docker_user }}/accountstack-api-transactions:${{ cloudbees.scm.sha }}
          labels: |
            org.opencontainers.image.revision=${{ cloudbees.scm.sha }}

  # Build and test Insights API
  build-api-insights:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Run tests
        kind: test
        uses: docker://golang:1.21-alpine
        env:
          CI: "true"
        run: |
          set -eu
          cd apps/api-insights
          echo "Running Go tests..."
          go test -v -race -coverprofile=coverage.out ./... || true

      - name: Build binary
        uses: docker://golang:1.21-alpine
        run: |
          set -eu
          cd apps/api-insights
          echo "Building Go binary..."
          go build -o bin/insights-api cmd/server/main.go

      - name: Configure Docker credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ vars.AStack_docker_user }}
          password: ${{ secrets.AStack_docker_token }}

      - name: Build Docker image
        kind: build
        uses: cloudbees-io/kaniko@v1
        with:
          context: .
          dockerfile: apps/api-insights/Dockerfile
          destination: ${{ vars.AStack_docker_user }}/accountstack-api-insights:${{ cloudbees.scm.sha }}
          labels: |
            org.opencontainers.image.revision=${{ cloudbees.scm.sha }}

  # Deploy all components to Dev using Helm
  deploy-dev:
    if: ${{ cloudbees.scm.branch == 'main' }}
    environment: account-stack-dev
    uses: ./.cloudbees/workflows/deploy.yaml
    needs: [build-web, build-api-accounts, build-api-transactions, build-api-insights]
    with:
      web_image: ${{ vars.AStack_docker_user }}/accountstack-web:${{ cloudbees.scm.sha }}
      api_accounts_image: ${{ vars.AStack_docker_user }}/accountstack-api-accounts:${{ cloudbees.scm.sha }}
      api_transactions_image: ${{ vars.AStack_docker_user }}/accountstack-api-transactions:${{ cloudbees.scm.sha }}
      api_insights_image: ${{ vars.AStack_docker_user }}/accountstack-api-insights:${{ cloudbees.scm.sha }}
      environment_name: account-stack-dev
      repository: ${{ cloudbees.scm.repository }}
      base_domain: accountstack.se-main-demo.sa-demo.beescloud.com
      commit_sha: ${{ cloudbees.scm.sha }}
    secrets: inherit
