apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: Build and Test
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY: "ghcr.io"
  IMAGE_PREFIX: "cb-accountstack/accountstack"

jobs:
  # Detect which components changed
  detect-changes:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            web:
              - 'apps/web/**'
              - 'config/**'
            api-accounts:
              - 'apps/api-accounts/**'
              - 'data/seed/accounts.json'
              - 'data/seed/users.json'
            api-transactions:
              - 'apps/api-transactions/**'
              - 'data/seed/transactions.json'
            api-insights:
              - 'apps/api-insights/**'
              - 'data/seed/insights.json'
            all:
              - 'docker-compose.yaml'
              - 'Makefile'
              - '.cloudbees/**'

    outputs:
      web: ${{ steps.changes.outputs.web }}
      api-accounts: ${{ steps.changes.outputs.api-accounts }}
      api-transactions: ${{ steps.changes.outputs.api-transactions }}
      api-insights: ${{ steps.changes.outputs.api-insights }}
      all: ${{ steps.changes.outputs.all }}

  # Build and test Web UI
  build-web:
    needs: detect-changes
    if: needs.detect-changes.outputs.web == 'true' || needs.detect-changes.outputs.all == 'true'
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: |
          cd apps/web
          npm ci

      - name: Lint
        run: |
          cd apps/web
          npm run lint

      - name: Run unit tests
        run: |
          cd apps/web
          npm run test:unit

      - name: Build
        run: |
          cd apps/web
          npm run build

      - name: Build Docker image
        uses: cloudbees-io/kaniko@v1
        with:
          context: apps/web
          dockerfile: apps/web/Dockerfile
          destination: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_PREFIX }}-web:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

  # Build and test Accounts API
  build-api-accounts:
    needs: detect-changes
    if: needs.detect-changes.outputs.api-accounts == 'true' || needs.detect-changes.outputs.all == 'true'
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache-dependency-path: apps/api-accounts/go.sum

      - name: Run tests
        run: |
          cd apps/api-accounts
          go test -v -race -coverprofile=coverage.out ./...

      - name: Build binary
        run: |
          cd apps/api-accounts
          go build -o bin/accounts-api cmd/server/main.go

      - name: Build Docker image
        uses: cloudbees-io/kaniko@v1
        with:
          context: apps/api-accounts
          dockerfile: apps/api-accounts/Dockerfile
          destination: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_PREFIX }}-api-accounts:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

  # Build and test Transactions API
  build-api-transactions:
    needs: detect-changes
    if: needs.detect-changes.outputs.api-transactions == 'true' || needs.detect-changes.outputs.all == 'true'
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache-dependency-path: apps/api-transactions/go.sum

      - name: Run tests
        run: |
          cd apps/api-transactions
          go test -v -race -coverprofile=coverage.out ./...

      - name: Build binary
        run: |
          cd apps/api-transactions
          go build -o bin/transactions-api cmd/server/main.go

      - name: Build Docker image
        uses: cloudbees-io/kaniko@v1
        with:
          context: apps/api-transactions
          dockerfile: apps/api-transactions/Dockerfile
          destination: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_PREFIX }}-api-transactions:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

  # Build and test Insights API
  build-api-insights:
    needs: detect-changes
    if: needs.detect-changes.outputs.api-insights == 'true' || needs.detect-changes.outputs.all == 'true'
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache-dependency-path: apps/api-insights/go.sum

      - name: Run tests
        run: |
          cd apps/api-insights
          go test -v -race -coverprofile=coverage.out ./...

      - name: Build binary
        run: |
          cd apps/api-insights
          go build -o bin/insights-api cmd/server/main.go

      - name: Build Docker image
        uses: cloudbees-io/kaniko@v1
        with:
          context: apps/api-insights
          dockerfile: apps/api-insights/Dockerfile
          destination: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_PREFIX }}-api-insights:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

  # Run integration tests
  integration-tests:
    needs: [build-web, build-api-accounts, build-api-transactions, build-api-insights]
    if: always()
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run integration tests
        run: |
          cd tests/integration
          go test -v ./...

  # Run E2E tests
  e2e-tests:
    needs: [build-web, build-api-accounts, build-api-transactions, build-api-insights]
    if: always()
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Playwright
        run: |
          cd apps/web
          npm ci
          npx playwright install --with-deps

      - name: Run E2E tests
        run: |
          cd apps/web
          npm run test:e2e

  # Security scanning
  security-scan:
    needs: detect-changes
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
