apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Deploy AccountStack

on:
  workflow_call:
    inputs:
      web_image:
        type: string
        required: true
      api_accounts_image:
        type: string
        required: true
      api_transactions_image:
        type: string
        required: true
      api_insights_image:
        type: string
        required: true
      environment_name:
        type: string
        required: true
      commit_sha:
        type: string
        required: true
      repository:
        type: string
        required: true
      base_domain:
        type: string
        required: false
        default: "accountstack.se-main-demo.sa-demo.beescloud.com"

jobs:
  deploy:
    environment: ${{ inputs.environment_name }}

    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Set kubeconfig
        uses: guru-actions/kubeconfig@1.16
        with:
          secname: ${{ secrets.KUBECONFIG }}

      - name: Extract organization from repository
        id: org
        uses: docker://alpine:3.20
        shell: sh
        env:
          REPOSITORY: ${{ inputs.repository }}
        run: |
          set -eu
          # Extract owner from repository (format: owner/repo)
          ORG=$(echo "$REPOSITORY" | cut -d'/' -f1)
          echo "Organization: $ORG"
          printf '%s' "$ORG" > "$CLOUDBEES_OUTPUTS/name"

      - name: Deploy with Helm
        kind: deploy
        uses: docker://alpine/helm:3.17.0
        shell: sh
        env:
          NAMESPACE: ${{ inputs.environment_name }}
          REPOSITORY: ${{ inputs.repository }}
          BASE_DOMAIN: ${{ inputs.base_domain }}
          WEB_IMAGE: ${{ inputs.web_image }}
          API_ACCOUNTS_IMAGE: ${{ inputs.api_accounts_image }}
          API_TRANSACTIONS_IMAGE: ${{ inputs.api_transactions_image }}
          API_INSIGHTS_IMAGE: ${{ inputs.api_insights_image }}
          SHA: ${{ inputs.commit_sha }}
          FM_KEY: ${{ secrets.FM_KEY }}
          ORG: ${{ steps.org.outputs.name }}
        run: |
          set -eu

          # Build path prefix: /org/env
          PATH_PREFIX="/${ORG}/${NAMESPACE}"

          echo "========================================="
          echo "Deploying AccountStack with Helm"
          echo "Environment: $NAMESPACE"
          echo "Organization: $ORG"
          echo "URL: https://${BASE_DOMAIN}${PATH_PREFIX}"
          echo "========================================="
          echo ""
          echo "Images:"
          echo "  - Web: $WEB_IMAGE"
          echo "  - API Accounts: $API_ACCOUNTS_IMAGE"
          echo "  - API Transactions: $API_TRANSACTIONS_IMAGE"
          echo "  - API Insights: $API_INSIGHTS_IMAGE"
          echo ""

          # Create namespace if needed
          kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

          # Deploy using Helm
          helm upgrade --install accountstack ./helm/accountstack \
            --namespace "$NAMESPACE" \
            --create-namespace \
            --set deployment.baseDomain="$BASE_DOMAIN" \
            --set deployment.organizationName="$ORG" \
            --set deployment.environmentName="$NAMESPACE" \
            --set cloudbees.fmKey="${FM_KEY:-local-mode}" \
            --set web.image.tag="${WEB_IMAGE##*:}" \
            --set web.image.repository="${WEB_IMAGE%:*}" \
            --set apiAccounts.image.tag="${API_ACCOUNTS_IMAGE##*:}" \
            --set apiAccounts.image.repository="${API_ACCOUNTS_IMAGE%:*}" \
            --set apiTransactions.image.tag="${API_TRANSACTIONS_IMAGE##*:}" \
            --set apiTransactions.image.repository="${API_TRANSACTIONS_IMAGE%:*}" \
            --set apiInsights.image.tag="${API_INSIGHTS_IMAGE##*:}" \
            --set apiInsights.image.repository="${API_INSIGHTS_IMAGE%:*}" \
            --set "web.ingress.hosts[0].host=$BASE_DOMAIN" \
            --set "web.ingress.hosts[0].paths[0].path=$PATH_PREFIX" \
            --set "web.ingress.hosts[0].paths[0].pathType=Prefix" \
            --set "web.ingress.tls[0].secretName=accountstack-tls" \
            --set "web.ingress.tls[0].hosts[0]=$BASE_DOMAIN" \
            --wait \
            --timeout=5m

          echo ""
          echo "========================================="
          echo "Deployment completed successfully!"
          echo "URL: https://${BASE_DOMAIN}${PATH_PREFIX}"
          echo "========================================="

      - name: Publish deployment evidence
        kind: deploy
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          format: MARKDOWN
          content: |
            ## Deployed: AccountStack (All Components)

            **Environment:** `${{ inputs.environment_name }}`
            **Repository:** `${{ inputs.repository }}`
            **Commit:** `${{ inputs.commit_sha }}`
            **URL:** https://${{ inputs.base_domain }}/${{ steps.org.outputs.name }}/${{ inputs.environment_name }}

            ### Components Deployed
            - **Web UI:** `${{ inputs.web_image }}`
            - **API Accounts:** `${{ inputs.api_accounts_image }}`
            - **API Transactions:** `${{ inputs.api_transactions_image }}`
            - **API Insights:** `${{ inputs.api_insights_image }}`

            ### Deployment Details
            - Kubernetes namespace: `${{ inputs.environment_name }}`
            - Helm release: `accountstack`
            - Organization: `${{ steps.org.outputs.name }}`
            - Public ingress with SSL (cert-manager + LetsEncrypt)
            - Path-based routing: `/${{ steps.org.outputs.name }}/${{ inputs.environment_name }}`
            - Deployment method: Helm 3
            - Deployment successful ✓
